/* GS Genesis — production bundle. Generated by build/build.js from index.html.
   Do NOT edit by hand; edit index.html and re-run `node build/build.js`. */

/* ===== tweaks-panel.jsx ===== */
(function () {
const __TWEAKS_STYLE = `
  .twk-panel{position:fixed;right:16px;bottom:16px;z-index:2147483646;width:280px;
    max-height:calc(100vh - 32px);display:flex;flex-direction:column;
    transform:scale(var(--dc-inv-zoom,1));transform-origin:bottom right;
    background:rgba(250,249,247,.78);color:#29261b;
    -webkit-backdrop-filter:blur(24px) saturate(160%);backdrop-filter:blur(24px) saturate(160%);
    border:.5px solid rgba(255,255,255,.6);border-radius:14px;
    box-shadow:0 1px 0 rgba(255,255,255,.5) inset,0 12px 40px rgba(0,0,0,.18);
    font:11.5px/1.4 ui-sans-serif,system-ui,-apple-system,sans-serif;overflow:hidden}
  .twk-hd{display:flex;align-items:center;justify-content:space-between;
    padding:10px 8px 10px 14px;cursor:move;user-select:none}
  .twk-hd b{font-size:12px;font-weight:600;letter-spacing:.01em}
  .twk-x{appearance:none;border:0;background:transparent;color:rgba(41,38,27,.55);
    width:22px;height:22px;border-radius:6px;cursor:default;font-size:13px;line-height:1}
  .twk-x:hover{background:rgba(0,0,0,.06);color:#29261b}
  .twk-body{padding:2px 14px 14px;display:flex;flex-direction:column;gap:10px;
    overflow-y:auto;overflow-x:hidden;min-height:0;
    scrollbar-width:thin;scrollbar-color:rgba(0,0,0,.15) transparent}
  .twk-body::-webkit-scrollbar{width:8px}
  .twk-body::-webkit-scrollbar-track{background:transparent;margin:2px}
  .twk-body::-webkit-scrollbar-thumb{background:rgba(0,0,0,.15);border-radius:4px;
    border:2px solid transparent;background-clip:content-box}
  .twk-body::-webkit-scrollbar-thumb:hover{background:rgba(0,0,0,.25);
    border:2px solid transparent;background-clip:content-box}
  .twk-row{display:flex;flex-direction:column;gap:5px}
  .twk-row-h{flex-direction:row;align-items:center;justify-content:space-between;gap:10px}
  .twk-lbl{display:flex;justify-content:space-between;align-items:baseline;
    color:rgba(41,38,27,.72)}
  .twk-lbl>span:first-child{font-weight:500}
  .twk-val{color:rgba(41,38,27,.5);font-variant-numeric:tabular-nums}

  .twk-sect{font-size:10px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;
    color:rgba(41,38,27,.45);padding:10px 0 0}
  .twk-sect:first-child{padding-top:0}

  .twk-field{appearance:none;box-sizing:border-box;width:100%;min-width:0;height:26px;padding:0 8px;
    border:.5px solid rgba(0,0,0,.1);border-radius:7px;
    background:rgba(255,255,255,.6);color:inherit;font:inherit;outline:none}
  .twk-field:focus{border-color:rgba(0,0,0,.25);background:rgba(255,255,255,.85)}
  select.twk-field{padding-right:22px;
    background-image:url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='10' height='6' viewBox='0 0 10 6'><path fill='rgba(0,0,0,.5)' d='M0 0h10L5 6z'/></svg>");
    background-repeat:no-repeat;background-position:right 8px center}

  .twk-slider{appearance:none;-webkit-appearance:none;width:100%;height:4px;margin:6px 0;
    border-radius:999px;background:rgba(0,0,0,.12);outline:none}
  .twk-slider::-webkit-slider-thumb{-webkit-appearance:none;appearance:none;
    width:14px;height:14px;border-radius:50%;background:#fff;
    border:.5px solid rgba(0,0,0,.12);box-shadow:0 1px 3px rgba(0,0,0,.2);cursor:default}
  .twk-slider::-moz-range-thumb{width:14px;height:14px;border-radius:50%;
    background:#fff;border:.5px solid rgba(0,0,0,.12);box-shadow:0 1px 3px rgba(0,0,0,.2);cursor:default}

  .twk-seg{position:relative;display:flex;padding:2px;border-radius:8px;
    background:rgba(0,0,0,.06);user-select:none}
  .twk-seg-thumb{position:absolute;top:2px;bottom:2px;border-radius:6px;
    background:rgba(255,255,255,.9);box-shadow:0 1px 2px rgba(0,0,0,.12);
    transition:left .15s cubic-bezier(.3,.7,.4,1),width .15s}
  .twk-seg.dragging .twk-seg-thumb{transition:none}
  .twk-seg button{appearance:none;position:relative;z-index:1;flex:1;border:0;
    background:transparent;color:inherit;font:inherit;font-weight:500;min-height:22px;
    border-radius:6px;cursor:default;padding:4px 6px;line-height:1.2;
    overflow-wrap:anywhere}

  .twk-toggle{position:relative;width:32px;height:18px;border:0;border-radius:999px;
    background:rgba(0,0,0,.15);transition:background .15s;cursor:default;padding:0}
  .twk-toggle[data-on="1"]{background:#34c759}
  .twk-toggle i{position:absolute;top:2px;left:2px;width:14px;height:14px;border-radius:50%;
    background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.25);transition:transform .15s}
  .twk-toggle[data-on="1"] i{transform:translateX(14px)}

  .twk-num{display:flex;align-items:center;box-sizing:border-box;min-width:0;height:26px;padding:0 0 0 8px;
    border:.5px solid rgba(0,0,0,.1);border-radius:7px;background:rgba(255,255,255,.6)}
  .twk-num-lbl{font-weight:500;color:rgba(41,38,27,.6);cursor:ew-resize;
    user-select:none;padding-right:8px}
  .twk-num input{flex:1;min-width:0;height:100%;border:0;background:transparent;
    font:inherit;font-variant-numeric:tabular-nums;text-align:right;padding:0 8px 0 0;
    outline:none;color:inherit;-moz-appearance:textfield}
  .twk-num input::-webkit-inner-spin-button,.twk-num input::-webkit-outer-spin-button{
    -webkit-appearance:none;margin:0}
  .twk-num-unit{padding-right:8px;color:rgba(41,38,27,.45)}

  .twk-btn{appearance:none;height:26px;padding:0 12px;border:0;border-radius:7px;
    background:rgba(0,0,0,.78);color:#fff;font:inherit;font-weight:500;cursor:default}
  .twk-btn:hover{background:rgba(0,0,0,.88)}
  .twk-btn.secondary{background:rgba(0,0,0,.06);color:inherit}
  .twk-btn.secondary:hover{background:rgba(0,0,0,.1)}

  .twk-swatch{appearance:none;-webkit-appearance:none;width:56px;height:22px;
    border:.5px solid rgba(0,0,0,.1);border-radius:6px;padding:0;cursor:default;
    background:transparent;flex-shrink:0}
  .twk-swatch::-webkit-color-swatch-wrapper{padding:0}
  .twk-swatch::-webkit-color-swatch{border:0;border-radius:5.5px}
  .twk-swatch::-moz-color-swatch{border:0;border-radius:5.5px}

  .twk-chips{display:flex;gap:6px}
  .twk-chip{position:relative;appearance:none;flex:1;min-width:0;height:46px;
    padding:0;border:0;border-radius:6px;overflow:hidden;cursor:default;
    box-shadow:0 0 0 .5px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.06);
    transition:transform .12s cubic-bezier(.3,.7,.4,1),box-shadow .12s}
  .twk-chip:hover{transform:translateY(-1px);
    box-shadow:0 0 0 .5px rgba(0,0,0,.18),0 4px 10px rgba(0,0,0,.12)}
  .twk-chip[data-on="1"]{box-shadow:0 0 0 1.5px rgba(0,0,0,.85),
    0 2px 6px rgba(0,0,0,.15)}
  .twk-chip>span{position:absolute;top:0;bottom:0;right:0;width:34%;
    display:flex;flex-direction:column;box-shadow:-1px 0 0 rgba(0,0,0,.1)}
  .twk-chip>span>i{flex:1;box-shadow:0 -1px 0 rgba(0,0,0,.1)}
  .twk-chip>span>i:first-child{box-shadow:none}
  .twk-chip svg{position:absolute;top:6px;left:6px;width:13px;height:13px;
    filter:drop-shadow(0 1px 1px rgba(0,0,0,.3))}
`;
function useTweaks(defaults) {
  const [values, setValues] = React.useState(defaults);
  const setTweak = React.useCallback((keyOrEdits, val) => {
    const edits = typeof keyOrEdits === 'object' && keyOrEdits !== null ? keyOrEdits : {
      [keyOrEdits]: val
    };
    setValues(prev => ({
      ...prev,
      ...edits
    }));
    window.parent.postMessage({
      type: '__edit_mode_set_keys',
      edits
    }, '*');
    window.dispatchEvent(new CustomEvent('tweakchange', {
      detail: edits
    }));
  }, []);
  return [values, setTweak];
}
function TweaksPanel({
  title = 'Tweaks',
  children
}) {
  const [open, setOpen] = React.useState(false);
  const dragRef = React.useRef(null);
  const offsetRef = React.useRef({
    x: 16,
    y: 16
  });
  const PAD = 16;
  const clampToViewport = React.useCallback(() => {
    const panel = dragRef.current;
    if (!panel) return;
    const w = panel.offsetWidth,
      h = panel.offsetHeight;
    const maxRight = Math.max(PAD, window.innerWidth - w - PAD);
    const maxBottom = Math.max(PAD, window.innerHeight - h - PAD);
    offsetRef.current = {
      x: Math.min(maxRight, Math.max(PAD, offsetRef.current.x)),
      y: Math.min(maxBottom, Math.max(PAD, offsetRef.current.y))
    };
    panel.style.right = offsetRef.current.x + 'px';
    panel.style.bottom = offsetRef.current.y + 'px';
  }, []);
  React.useEffect(() => {
    if (!open) return;
    clampToViewport();
    if (typeof ResizeObserver === 'undefined') {
      window.addEventListener('resize', clampToViewport);
      return () => window.removeEventListener('resize', clampToViewport);
    }
    const ro = new ResizeObserver(clampToViewport);
    ro.observe(document.documentElement);
    return () => ro.disconnect();
  }, [open, clampToViewport]);
  React.useEffect(() => {
    const onMsg = e => {
      const t = e?.data?.type;
      if (t === '__activate_edit_mode') setOpen(true);else if (t === '__deactivate_edit_mode') setOpen(false);
    };
    window.addEventListener('message', onMsg);
    window.parent.postMessage({
      type: '__edit_mode_available'
    }, '*');
    return () => window.removeEventListener('message', onMsg);
  }, []);
  const dismiss = () => {
    setOpen(false);
    window.parent.postMessage({
      type: '__edit_mode_dismissed'
    }, '*');
  };
  const onDragStart = e => {
    const panel = dragRef.current;
    if (!panel) return;
    const r = panel.getBoundingClientRect();
    const sx = e.clientX,
      sy = e.clientY;
    const startRight = window.innerWidth - r.right;
    const startBottom = window.innerHeight - r.bottom;
    const move = ev => {
      offsetRef.current = {
        x: startRight - (ev.clientX - sx),
        y: startBottom - (ev.clientY - sy)
      };
      clampToViewport();
    };
    const up = () => {
      window.removeEventListener('mousemove', move);
      window.removeEventListener('mouseup', up);
    };
    window.addEventListener('mousemove', move);
    window.addEventListener('mouseup', up);
  };
  if (!open) return null;
  return React.createElement(React.Fragment, null, React.createElement("style", null, __TWEAKS_STYLE), React.createElement("div", {
    ref: dragRef,
    className: "twk-panel",
    "data-omelette-chrome": "",
    style: {
      right: offsetRef.current.x,
      bottom: offsetRef.current.y
    }
  }, React.createElement("div", {
    className: "twk-hd",
    onMouseDown: onDragStart
  }, React.createElement("b", null, title), React.createElement("button", {
    className: "twk-x",
    "aria-label": "Close tweaks",
    onMouseDown: e => e.stopPropagation(),
    onClick: dismiss
  }, "\u2715")), React.createElement("div", {
    className: "twk-body"
  }, children)));
}
function TweakSection({
  label,
  children
}) {
  return React.createElement(React.Fragment, null, React.createElement("div", {
    className: "twk-sect"
  }, label), children);
}
function TweakRow({
  label,
  value,
  children,
  inline = false
}) {
  return React.createElement("div", {
    className: inline ? 'twk-row twk-row-h' : 'twk-row'
  }, React.createElement("div", {
    className: "twk-lbl"
  }, React.createElement("span", null, label), value != null && React.createElement("span", {
    className: "twk-val"
  }, value)), children);
}
function TweakSlider({
  label,
  value,
  min = 0,
  max = 100,
  step = 1,
  unit = '',
  onChange
}) {
  return React.createElement(TweakRow, {
    label: label,
    value: `${value}${unit}`
  }, React.createElement("input", {
    type: "range",
    className: "twk-slider",
    min: min,
    max: max,
    step: step,
    value: value,
    onChange: e => onChange(Number(e.target.value))
  }));
}
function TweakToggle({
  label,
  value,
  onChange
}) {
  return React.createElement("div", {
    className: "twk-row twk-row-h"
  }, React.createElement("div", {
    className: "twk-lbl"
  }, React.createElement("span", null, label)), React.createElement("button", {
    type: "button",
    className: "twk-toggle",
    "data-on": value ? '1' : '0',
    role: "switch",
    "aria-checked": !!value,
    onClick: () => onChange(!value)
  }, React.createElement("i", null)));
}
function TweakRadio({
  label,
  value,
  options,
  onChange
}) {
  const trackRef = React.useRef(null);
  const [dragging, setDragging] = React.useState(false);
  const valueRef = React.useRef(value);
  valueRef.current = value;
  const labelLen = o => String(typeof o === 'object' ? o.label : o).length;
  const maxLen = options.reduce((m, o) => Math.max(m, labelLen(o)), 0);
  const fitsAsSegments = maxLen <= ({
    2: 16,
    3: 10
  }[options.length] ?? 0);
  if (!fitsAsSegments) {
    const resolve = s => {
      const m = options.find(o => String(typeof o === 'object' ? o.value : o) === s);
      return m === undefined ? s : typeof m === 'object' ? m.value : m;
    };
    return React.createElement(TweakSelect, {
      label: label,
      value: value,
      options: options,
      onChange: s => onChange(resolve(s))
    });
  }
  const opts = options.map(o => typeof o === 'object' ? o : {
    value: o,
    label: o
  });
  const idx = Math.max(0, opts.findIndex(o => o.value === value));
  const n = opts.length;
  const segAt = clientX => {
    const r = trackRef.current.getBoundingClientRect();
    const inner = r.width - 4;
    const i = Math.floor((clientX - r.left - 2) / inner * n);
    return opts[Math.max(0, Math.min(n - 1, i))].value;
  };
  const onPointerDown = e => {
    setDragging(true);
    const v0 = segAt(e.clientX);
    if (v0 !== valueRef.current) onChange(v0);
    const move = ev => {
      if (!trackRef.current) return;
      const v = segAt(ev.clientX);
      if (v !== valueRef.current) onChange(v);
    };
    const up = () => {
      setDragging(false);
      window.removeEventListener('pointermove', move);
      window.removeEventListener('pointerup', up);
    };
    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', up);
  };
  return React.createElement(TweakRow, {
    label: label
  }, React.createElement("div", {
    ref: trackRef,
    role: "radiogroup",
    onPointerDown: onPointerDown,
    className: dragging ? 'twk-seg dragging' : 'twk-seg'
  }, React.createElement("div", {
    className: "twk-seg-thumb",
    style: {
      left: `calc(2px + ${idx} * (100% - 4px) / ${n})`,
      width: `calc((100% - 4px) / ${n})`
    }
  }), opts.map(o => React.createElement("button", {
    key: o.value,
    type: "button",
    role: "radio",
    "aria-checked": o.value === value
  }, o.label))));
}
function TweakSelect({
  label,
  value,
  options,
  onChange
}) {
  return React.createElement(TweakRow, {
    label: label
  }, React.createElement("select", {
    className: "twk-field",
    value: value,
    onChange: e => onChange(e.target.value)
  }, options.map(o => {
    const v = typeof o === 'object' ? o.value : o;
    const l = typeof o === 'object' ? o.label : o;
    return React.createElement("option", {
      key: v,
      value: v
    }, l);
  })));
}
function TweakText({
  label,
  value,
  placeholder,
  onChange
}) {
  return React.createElement(TweakRow, {
    label: label
  }, React.createElement("input", {
    className: "twk-field",
    type: "text",
    value: value,
    placeholder: placeholder,
    onChange: e => onChange(e.target.value)
  }));
}
function TweakNumber({
  label,
  value,
  min,
  max,
  step = 1,
  unit = '',
  onChange
}) {
  const clamp = n => {
    if (min != null && n < min) return min;
    if (max != null && n > max) return max;
    return n;
  };
  const startRef = React.useRef({
    x: 0,
    val: 0
  });
  const onScrubStart = e => {
    e.preventDefault();
    startRef.current = {
      x: e.clientX,
      val: value
    };
    const decimals = (String(step).split('.')[1] || '').length;
    const move = ev => {
      const dx = ev.clientX - startRef.current.x;
      const raw = startRef.current.val + dx * step;
      const snapped = Math.round(raw / step) * step;
      onChange(clamp(Number(snapped.toFixed(decimals))));
    };
    const up = () => {
      window.removeEventListener('pointermove', move);
      window.removeEventListener('pointerup', up);
    };
    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', up);
  };
  return React.createElement("div", {
    className: "twk-num"
  }, React.createElement("span", {
    className: "twk-num-lbl",
    onPointerDown: onScrubStart
  }, label), React.createElement("input", {
    type: "number",
    value: value,
    min: min,
    max: max,
    step: step,
    onChange: e => onChange(clamp(Number(e.target.value)))
  }), unit && React.createElement("span", {
    className: "twk-num-unit"
  }, unit));
}
function __twkIsLight(hex) {
  const h = String(hex).replace('#', '');
  const x = h.length === 3 ? h.replace(/./g, c => c + c) : h.padEnd(6, '0');
  const n = parseInt(x.slice(0, 6), 16);
  if (Number.isNaN(n)) return true;
  const r = n >> 16 & 255,
    g = n >> 8 & 255,
    b = n & 255;
  return r * 299 + g * 587 + b * 114 > 148000;
}
const __TwkCheck = ({
  light
}) => React.createElement("svg", {
  viewBox: "0 0 14 14",
  "aria-hidden": "true"
}, React.createElement("path", {
  d: "M3 7.2 5.8 10 11 4.2",
  fill: "none",
  strokeWidth: "2.2",
  strokeLinecap: "round",
  strokeLinejoin: "round",
  stroke: light ? 'rgba(0,0,0,.78)' : '#fff'
}));
function TweakColor({
  label,
  value,
  options,
  onChange
}) {
  if (!options || !options.length) {
    return React.createElement("div", {
      className: "twk-row twk-row-h"
    }, React.createElement("div", {
      className: "twk-lbl"
    }, React.createElement("span", null, label)), React.createElement("input", {
      type: "color",
      className: "twk-swatch",
      value: value,
      onChange: e => onChange(e.target.value)
    }));
  }
  const key = o => String(JSON.stringify(o)).toLowerCase();
  const cur = key(value);
  return React.createElement(TweakRow, {
    label: label
  }, React.createElement("div", {
    className: "twk-chips",
    role: "radiogroup"
  }, options.map((o, i) => {
    const colors = Array.isArray(o) ? o : [o];
    const [hero, ...rest] = colors;
    const sup = rest.slice(0, 4);
    const on = key(o) === cur;
    return React.createElement("button", {
      key: i,
      type: "button",
      className: "twk-chip",
      role: "radio",
      "aria-checked": on,
      "data-on": on ? '1' : '0',
      "aria-label": colors.join(', '),
      title: colors.join(' · '),
      style: {
        background: hero
      },
      onClick: () => onChange(o)
    }, sup.length > 0 && React.createElement("span", null, sup.map((c, j) => React.createElement("i", {
      key: j,
      style: {
        background: c
      }
    }))), on && React.createElement(__TwkCheck, {
      light: __twkIsLight(hero)
    }));
  })));
}
function TweakButton({
  label,
  onClick,
  secondary = false
}) {
  return React.createElement("button", {
    type: "button",
    className: secondary ? 'twk-btn secondary' : 'twk-btn',
    onClick: onClick
  }, label);
}
Object.assign(window, {
  useTweaks,
  TweaksPanel,
  TweakSection,
  TweakRow,
  TweakSlider,
  TweakToggle,
  TweakRadio,
  TweakSelect,
  TweakText,
  TweakNumber,
  TweakColor,
  TweakButton
});
})();

/* ===== i18n.jsx ===== */
(function () {
const I18N = {
  zh: {
    locale: "zh",
    nav: {
      about: "關於我們",
      services: "業務範圍",
      philosophy: "投資哲學",
      team: "經營團隊",
      space: "辦公環境",
      milestones: "發展藍圖",
      contact: "聯絡我們",
      menu: "選單",
      consult: "預約諮詢"
    },
    hero: {
      eyebrow: "GS Genesis · Est. 2025",
      title1: "穿越市場循環",
      title2: "創造世代資本",
      en: "Where Discipline Meets Conviction.",
      sub: "Genesis International Capital 是 2025 年成立於台中的金融科技新創，以 AI 驅動量化交易為核心。我們正在打造自主研發的交易系統，並堅持一個標準——所有策略，都必須以自有資金在實盤中證明自己。",
      cta1: "了解我們",
      cta2: "預約諮詢",
      ticker: ["AI 量化交易 · AI QUANT", "自營交易 · PROP TRADING", "AI 應用開發 · AI SOLUTIONS", "風險控制 · RISK MANAGEMENT"],
      scroll: "向下探索 SCROLL"
    },
    about: {
      num: "01 / ABOUT",
      title: "源於信念，",
      titleEm: "Genesis.",
      titleSub: "成於紀律。",
      lead: "「創世紀」之名，源於我們對於資本市場的初心——在波動與不確定之中，建立屬於下一個世代的財富根基。",
      body1: "GS 創世紀國際投資（Genesis International Capital）是 2025 年成立的金融科技新創，總部位於台中，以 AI 驅動量化交易為核心。我們正在打造自主研發的交易系統，並堅持以內部實盤驗證——真實績效，是技術實力的唯一標準。",
      body2: "從自營交易出發，我們正積極訓練 AI 量化模型實戰，並規劃兩大事業線：AI 整合解決方案與 AI 應用產品，持續推進 AI 技術在金融領域的商業落地。",
      stats: [{
        num: "2025",
        unit: "年",
        label: "成立於台中"
      }, {
        num: "2,000",
        unit: "萬",
        label: "實收資本額"
      }, {
        num: "11",
        unit: "+",
        label: "團隊持續擴編"
      }, {
        num: "24",
        unit: "/7",
        label: "全球市場監控"
      }]
    },
    services: {
      num: "02 / SERVICES",
      title: "業務範圍",
      titleEn: "What We Trade.",
      lead: "從股票、期貨與海外股票的自營交易，到 AI 應用軟體開發與顧問服務，GS 創世紀以 AI 為核心，覆蓋交易、軟體與顧問三大領域。",
      items: [{
        en: "Proprietary Trading",
        zh: "自營交易",
        desc: "以公司自有資金進行股票、期貨與海外股票自營交易，搭配嚴謹的風險控制，以內部實盤驗證為交易準則。"
      }, {
        en: "AI Quant Strategies",
        zh: "AI 量化策略",
        desc: "正在自主研發 AI 量化模型與輔助交易軟體，持續以實戰訓練模型——真實績效是技術實力的唯一標準。"
      }, {
        en: "AI Solutions & Applications",
        zh: "AI 整合解決方案",
        desc: "開發各類 AI 應用軟體、AI 程式撰寫與輔助程式工具，推進 AI 技術在金融領域的商業落地。"
      }, {
        en: "Financial Advisory",
        zh: "金融顧問",
        desc: "提供金融與企業管理顧問服務，協助客戶導入量化方法與 AI 工具，建立可驗證的決策流程。"
      }]
    },
    philosophy: {
      num: "03 / PHILOSOPHY",
      title: "投資哲學",
      titleEn: "How We Think.",
      quote1: "以 AI 驅動交易，",
      quote2: "以實盤驗證實力，",
      quote3: "以人才創造未來。",
      pillars: [{
        en: "AI-Native",
        zh: "AI 原生",
        desc: "程式由 AI Agent 撰寫；擴充、優化、Review 與成本控管，是新時代軟體工程的核心能力。"
      }, {
        en: "Proven Live",
        zh: "實盤驗證",
        desc: "所有策略與系統，都必須以自有資金通過實盤驗證——真實績效是技術實力的唯一標準。"
      }, {
        en: "People First",
        zh: "以人為本",
        desc: "公司人少、層級扁平，尊重成員的自我意志，提供最好的環境與最大的發揮空間。"
      }]
    },
    team: {
      num: "04 / TEAM",
      title: "經營團隊",
      titleEn: "The Architects.",
      lead: "我們是一支持續成長的新創團隊，層級扁平、以人為本，由 AI、交易與策略三個核心部門組成。我們正在尋找兼具技術深度與市場敏銳度的優秀人才——歡迎極客與黑客加入，共同打造下一代智慧金融基礎設施。",
      members: [{
        init: "A",
        name: "AI 部門",
        role: "AI Lab",
        bio: "AI Agent 驅動的軟體開發、模型訓練，與各類 AI 應用產品的打造。"
      }, {
        init: "T",
        name: "交易部門",
        role: "Trading Desk",
        bio: "股票、期貨與海外股票自營交易，於嚴謹風控下實盤執行。"
      }, {
        init: "S",
        name: "策略部門",
        role: "Strategy Research",
        bio: "量化策略研究與回測，為交易系統提供可驗證的決策邏輯。"
      }]
    },
    space: {
      num: "05 / SPACE",
      title: "辦公環境",
      titleEn: "Our Space.",
      lead: "位於台中的辦公室，是我們交易、研發與思考的所在。一面落地窗收進城市夜景，一張桌、兩個螢幕——策略，就在這裡誕生。",
      items: [{
        img: "data/images/office_build.png",
        label: "Future HQ · 示意圖",
        title: "未來總部規劃",
        desc: "規劃興建中的自有大樓——示意圖,非現址。"
      }, {
        img: "data/images/workspace.png",
        label: "The Desk",
        title: "交易與研發桌",
        desc: "雙螢幕、實盤環境，AI 與人協作的第一線。"
      }]
    },
    milestones: {
      num: "06 / ROADMAP",
      title: "發展藍圖",
      titleEn: "The Road Ahead.",
      lead: "2025 年，我們從一張交易桌出發。這是我們正在走、以及接下來要走的路。",
      items: [{
        year: "2025",
        title: "公司成立",
        desc: "GS 創世紀國際投資於台中成立，以自營交易為核心業務啟動運營。"
      }, {
        year: "2025",
        title: "AI 原生開發",
        desc: "從第一天起，軟體即由 AI Agent 撰寫——擴充、優化與 Review 是工程核心。"
      }, {
        year: "2026",
        title: "模型實戰訓練",
        desc: "AI 量化模型持續以實盤訓練，以自有資金累積經過驗證的真實績效。"
      }, {
        year: "2026",
        title: "交易系統自主化",
        desc: "完成自主研發交易系統建置，覆蓋股票、期貨與海外股票市場。"
      }, {
        year: "2027",
        title: "AI 整合解決方案",
        desc: "將內部驗證的 AI 能力產品化，推出企業級整合解決方案。"
      }, {
        year: "2027+",
        title: "AI 應用產品線",
        desc: "拓展各類 AI 應用產品，打造下一代智慧金融基礎設施。"
      }]
    },
    contact: {
      num: "07 / CONTACT",
      title: "預約",
      titleEm: "對話",
      titleEn: "Begin a Conversation.",
      lead: "若您是潛在合作夥伴或希望深入了解 GS 創世紀的策略框架，歡迎透過以下方式直接與我們聯繫。",
      form: {
        name: "姓名 NAME",
        company: "公司／機構 COMPANY",
        email: "電子郵件 EMAIL",
        phone: "聯絡電話 PHONE",
        topic: "諮詢類別 TOPIC",
        message: "留言 MESSAGE",
        submit: "送出申請",
        topics: ["合作洽談", "策略諮詢", "媒體聯絡", "求職應徵", "其他"]
      },
      info: [{
        label: "Address",
        val: "台中市北屯區后庄路 41 號 10 樓-41"
      }, {
        label: "Contact",
        val: "Joker游"
      }, {
        label: "Phone",
        val: "04-2299-1928"
      }, {
        label: "Email",
        val: "gsinvest@gsinvest.com.tw"
      }, {
        label: "Hours",
        val: "週一至週四  09:00 – 17:30 (GMT+8)"
      }]
    },
    footer: {
      tagline: "創世紀國際投資股份有限公司\n以紀律之名，築世代之資。",
      explore: "探索",
      explore_links: ["關於我們", "業務範圍", "投資哲學", "經營團隊", "發展藍圖"],
      legal: "法務",
      legal_links: ["條款與條件", "隱私權政策", "Cookie 設定", "風險揭露"],
      connect: "聯絡",
      connect_links: ["LinkedIn", "gsinvest@gsinvest.com.tw", "04-2299-1928"],
      copy: "© 2026 GS Genesis International Investment Co., Ltd. All rights reserved.",
      built: "台中 · 台灣"
    },
    disclaimer: "本網站所載內容僅供一般資訊用途，不構成任何投資建議、招攬或要約。投資涉及風險，過去績效不代表未來表現。做出任何投資決策前，請諮詢合格專業顧問。"
  },
  en: {
    locale: "en",
    nav: {
      about: "About",
      services: "Services",
      philosophy: "Philosophy",
      team: "Team",
      space: "Our Space",
      milestones: "Roadmap",
      contact: "Contact",
      menu: "Menu",
      consult: "Book a Call"
    },
    hero: {
      eyebrow: "GS Genesis · Est. 2025",
      title1: "Compounding Across",
      title2: "Market Cycles.",
      en: "Where Discipline Meets Conviction.",
      sub: "Genesis International Capital is a fintech startup founded in Taichung in 2025, built around AI-driven quantitative trading. We are building our own trading systems to one standard — every strategy must prove itself with our own capital in live markets.",
      cta1: "Discover Genesis",
      cta2: "Book a Call",
      ticker: ["AI QUANT TRADING", "PROPRIETARY TRADING", "AI SOLUTIONS", "RISK MANAGEMENT"],
      scroll: "SCROLL TO EXPLORE"
    },
    about: {
      num: "01 / ABOUT",
      title: "Built on conviction.",
      titleEm: "Genesis.",
      titleSub: "Run with discipline.",
      lead: "We named the firm Genesis because every disciplined return compounds from one principled decision — the origin of generational capital.",
      body1: "GS Genesis (Genesis International Capital) is a fintech startup founded in Taichung in 2025, built around AI-driven quantitative trading. We are building our trading systems in-house, to one standard: real performance, proven with our own capital in live markets.",
      body2: "Starting from a proprietary trading core, we are training our AI quant models in live markets and planning two business lines — AI integration solutions and AI application products — to bring AI to commercial reality in finance.",
      stats: [{
        num: "2025",
        unit: "",
        label: "Founded in Taichung"
      }, {
        num: "20",
        unit: "M",
        label: "Paid-in capital (TWD)"
      }, {
        num: "11",
        unit: "+",
        label: "Team — and growing"
      }, {
        num: "24",
        unit: "/7",
        label: "Global market coverage"
      }]
    },
    services: {
      num: "02 / SERVICES",
      title: "What we trade.",
      titleEn: "Services.",
      lead: "From proprietary trading in equities, futures and overseas stocks to AI software and advisory, Genesis builds everything around one core: AI.",
      items: [{
        en: "Proprietary Trading",
        zh: "Prop Desk",
        desc: "Trading the firm's own capital across equities, futures and overseas stocks — under strict risk control, with live validation as the standard for every strategy."
      }, {
        en: "AI Quant Strategies",
        zh: "AI Quant",
        desc: "Developing our own AI quant models and trading-assist software, trained in live markets — real performance is the only standard of technical strength."
      }, {
        en: "AI Solutions & Applications",
        zh: "AI Apps",
        desc: "AI application software, AI-assisted programming and developer tooling — bringing AI to commercial reality in finance."
      }, {
        en: "Financial Advisory",
        zh: "Advisory",
        desc: "Financial and management consulting that helps clients adopt quantitative methods and AI tools with auditable decision processes."
      }]
    },
    philosophy: {
      num: "03 / PHILOSOPHY",
      title: "How we think.",
      titleEn: "Philosophy.",
      quote1: "AI drives the trade.",
      quote2: "Live markets prove it.",
      quote3: "People build the future.",
      pillars: [{
        en: "AI-Native",
        zh: "AI",
        desc: "Code is written by AI agents; scaling, optimization, review and token economics are the new core of software engineering."
      }, {
        en: "Proven Live",
        zh: "Live",
        desc: "Every strategy and system must prove itself with our own capital in live markets — real performance is the only proof."
      }, {
        en: "People First",
        zh: "People",
        desc: "A small team with a flat hierarchy: we respect individual will and give you the best environment and the widest room to create."
      }]
    },
    team: {
      num: "04 / TEAM",
      title: "The architects.",
      titleEn: "Team.",
      lead: "We are a growing startup with a flat hierarchy, built around three core teams: AI, trading and strategy. We are looking for people with both technical depth and market instinct — geeks and hackers welcome — to build the next generation of intelligent financial infrastructure.",
      members: [{
        init: "A",
        name: "AI Lab",
        role: "Artificial Intelligence",
        bio: "AI-agent-driven development, model training and AI application products."
      }, {
        init: "T",
        name: "Trading Desk",
        role: "Proprietary Trading",
        bio: "Equities, futures and overseas stocks — live execution under strict risk control."
      }, {
        init: "S",
        name: "Strategy Research",
        role: "Quant Strategy",
        bio: "Quantitative research and backtesting that feed verifiable logic into the trading systems."
      }]
    },
    space: {
      num: "05 / SPACE",
      title: "Our space.",
      titleEn: "Our Space.",
      lead: "Our Taichung office is where we trade, build and think. A floor-to-ceiling window frames the city at night; one desk, two monitors — this is where strategy is born.",
      items: [{
        img: "data/images/office_build.png",
        label: "Future HQ · Concept",
        title: "Future Headquarters",
        desc: "A planned building, shown as a concept rendering — not our current address."
      }, {
        img: "data/images/workspace.png",
        label: "The Desk",
        title: "Trading & Research",
        desc: "Dual monitors and a live-market setup — the front line of human-AI collaboration."
      }]
    },
    milestones: {
      num: "06 / ROADMAP",
      title: "The road ahead.",
      titleEn: "Roadmap.",
      lead: "Founded in 2025 — one trading desk, and a clear path forward.",
      items: [{
        year: "2025",
        title: "Firm founded",
        desc: "Genesis is established in Taichung with proprietary trading as the core business."
      }, {
        year: "2025",
        title: "AI-native from day one",
        desc: "Software is written by AI agents from the start — scaling, optimization and review are the engineering core."
      }, {
        year: "2026",
        title: "Models go live",
        desc: "AI quant models train in live markets, building a verified track record with our own capital."
      }, {
        year: "2026",
        title: "In-house systems",
        desc: "Self-developed trading systems cover equities, futures and overseas stock markets."
      }, {
        year: "2027",
        title: "AI solutions",
        desc: "Internally proven AI capabilities are productized into enterprise integration solutions."
      }, {
        year: "2027+",
        title: "AI product lines",
        desc: "AI application products expand — building the next generation of intelligent financial infrastructure."
      }]
    },
    contact: {
      num: "07 / CONTACT",
      title: "Begin a",
      titleEm: "conversation",
      titleEn: "Contact.",
      lead: "If you are a potential partner or would like to learn more about the Genesis framework, reach us directly through the channels below.",
      form: {
        name: "NAME",
        company: "COMPANY",
        email: "EMAIL",
        phone: "PHONE",
        topic: "TOPIC",
        message: "MESSAGE",
        submit: "Submit request",
        topics: ["Partnership", "Strategy inquiry", "Press & media", "Careers", "Other"]
      },
      info: [{
        label: "Address",
        val: "10F.-41, No. 41, Houzhuang Rd.,\nBeitun Dist., Taichung, Taiwan"
      }, {
        label: "Contact",
        val: "Joker游"
      }, {
        label: "Phone",
        val: "+886 4 2299 1928"
      }, {
        label: "Email",
        val: "gsinvest@gsinvest.com.tw"
      }, {
        label: "Hours",
        val: "Mon – Thu  09:00 – 17:30 (GMT+8)"
      }]
    },
    footer: {
      tagline: "Genesis International Investment Co., Ltd.\nCompounding capital. Across generations.",
      explore: "Explore",
      explore_links: ["About", "Services", "Philosophy", "Team", "Roadmap"],
      legal: "Legal",
      legal_links: ["Terms & Conditions", "Privacy Policy", "Cookie Settings", "Risk Disclosure"],
      connect: "Connect",
      connect_links: ["LinkedIn", "gsinvest@gsinvest.com.tw", "+886 4 2299 1928"],
      copy: "© 2026 GS Genesis International Investment Co., Ltd. All rights reserved.",
      built: "Taichung · Taiwan"
    },
    disclaimer: "The contents of this website are for general information only and do not constitute investment advice, solicitation or offer of any kind. Investing involves risk; past performance is no guarantee of future results. Please consult a qualified professional before making any investment decision."
  }
};
window.I18N = I18N;
})();

/* ===== three-hero.jsx ===== */
(function () {
const {
  useEffect,
  useRef,
  useState
} = React;
function useThreeReady() {
  const [ready, setReady] = useState(() => typeof THREE !== "undefined");
  useEffect(() => {
    if (ready) return;
    let id;
    const mark = () => {
      setReady(true);
      if (id) clearInterval(id);
    };
    if (typeof THREE !== "undefined") {
      mark();
      return;
    }
    window.addEventListener("threeready", mark, {
      once: true
    });
    id = setInterval(() => {
      if (typeof THREE !== "undefined") mark();
    }, 120);
    return () => {
      window.removeEventListener("threeready", mark);
      if (id) clearInterval(id);
    };
  }, [ready]);
  return ready;
}
function ThreeHero({
  goldColor = "#D4AF37",
  rotationSpeed = 1,
  particleDensity = 1,
  page = 0
}) {
  const mountRef = useRef(null);
  const sceneRef = useRef(null);
  const pageRef = useRef(page);
  const speedRef = useRef(rotationSpeed);
  const threeReady = useThreeReady();
  useEffect(() => {
    pageRef.current = page;
  }, [page]);
  useEffect(() => {
    speedRef.current = rotationSpeed;
  }, [rotationSpeed]);
  useEffect(() => {
    const mount = mountRef.current;
    if (!mount || typeof THREE === "undefined") return;
    const width = mount.clientWidth;
    const height = mount.clientHeight;
    const scene = new THREE.Scene();
    scene.fog = new THREE.FogExp2(0x070707, 0.028);
    const camera = new THREE.PerspectiveCamera(45, width / height, 0.1, 100);
    camera.position.set(0, 0, 12);
    const FIT_RADIUS = 6.4;
    const fitCamera = (w, h) => {
      const aspect = w / h;
      const vFov = camera.fov * Math.PI / 180;
      const distH = FIT_RADIUS / Math.tan(vFov / 2);
      const distW = FIT_RADIUS / (Math.tan(vFov / 2) * aspect);
      camera.position.z = Math.max(distH, distW, 11);
    };
    fitCamera(width, height);
    const renderer = new THREE.WebGLRenderer({
      antialias: true,
      alpha: true
    });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.setSize(width, height);
    renderer.setClearColor(0x000000, 0);
    renderer.outputEncoding = THREE.sRGBEncoding;
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1.1;
    mount.appendChild(renderer.domElement);
    const ambient = new THREE.AmbientLight(0x1a1610, 0.3);
    scene.add(ambient);
    const hemi = new THREE.HemisphereLight(0xffd86b, 0x0a0a0a, 0.4);
    scene.add(hemi);
    const keyLight = new THREE.PointLight(0xffd86b, 3.5, 30);
    keyLight.position.set(6, 6, 8);
    scene.add(keyLight);
    const fillLight = new THREE.PointLight(0xfff0c0, 1.4, 25);
    fillLight.position.set(-7, -2, 6);
    scene.add(fillLight);
    const rimLight = new THREE.PointLight(0xffb84a, 4, 20);
    rimLight.position.set(-3, 3, -8);
    scene.add(rimLight);
    const bottomLight = new THREE.PointLight(0xb8860b, 1.5, 20);
    bottomLight.position.set(2, -6, 4);
    scene.add(bottomLight);
    const goldHex = new THREE.Color(goldColor);
    const goldMaterial = new THREE.MeshStandardMaterial({
      color: goldHex,
      metalness: 1.0,
      roughness: 0.18,
      emissive: new THREE.Color(0x2a1f08),
      emissiveIntensity: 0.3
    });
    const goldDarkMaterial = new THREE.MeshStandardMaterial({
      color: new THREE.Color(0x6b4f12),
      metalness: 1.0,
      roughness: 0.35
    });
    const group = new THREE.Group();
    scene.add(group);
    const coreGeom = new THREE.DodecahedronGeometry(1.8, 0);
    const core = new THREE.Mesh(coreGeom, goldMaterial);
    group.add(core);
    const edgesGeom = new THREE.EdgesGeometry(coreGeom);
    const edgesMat = new THREE.LineBasicMaterial({
      color: 0xfff0a0,
      transparent: true,
      opacity: 0.4
    });
    const edges = new THREE.LineSegments(edgesGeom, edgesMat);
    core.add(edges);
    const orbiters = [];
    const orbiterGeom = new THREE.OctahedronGeometry(0.28, 0);
    for (let i = 0; i < 8; i++) {
      const m = new THREE.Mesh(orbiterGeom, goldMaterial);
      const angle = i / 8 * Math.PI * 2;
      const radius = 3.2;
      m.position.set(Math.cos(angle) * radius, Math.sin(angle) * 0.5, Math.sin(angle) * radius);
      m.userData = {
        angle,
        radius,
        phase: i * 0.4
      };
      group.add(m);
      orbiters.push(m);
    }
    const ringGeom1 = new THREE.TorusGeometry(2.5, 0.025, 8, 128);
    const ring1 = new THREE.Mesh(ringGeom1, goldMaterial);
    ring1.rotation.x = Math.PI / 2.5;
    group.add(ring1);
    const ringGeom2 = new THREE.TorusGeometry(3.0, 0.02, 8, 128);
    const ring2 = new THREE.Mesh(ringGeom2, goldDarkMaterial);
    ring2.rotation.x = Math.PI / 3.5;
    ring2.rotation.z = Math.PI / 6;
    group.add(ring2);
    const ringGeom3 = new THREE.TorusGeometry(3.7, 0.012, 6, 128);
    const ring3 = new THREE.Mesh(ringGeom3, goldDarkMaterial);
    ring3.rotation.x = Math.PI / 2;
    ring3.rotation.y = Math.PI / 5;
    group.add(ring3);
    const particleCount = Math.floor(800 * particleDensity);
    const particlesGeom = new THREE.BufferGeometry();
    const positions = new Float32Array(particleCount * 3);
    const scales = new Float32Array(particleCount);
    for (let i = 0; i < particleCount; i++) {
      const r = 4 + Math.random() * 10;
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(2 * Math.random() - 1);
      positions[i * 3] = r * Math.sin(phi) * Math.cos(theta);
      positions[i * 3 + 1] = (Math.random() - 0.5) * 14;
      positions[i * 3 + 2] = r * Math.sin(phi) * Math.sin(theta);
      scales[i] = Math.random();
    }
    particlesGeom.setAttribute("position", new THREE.BufferAttribute(positions, 3));
    particlesGeom.setAttribute("scale", new THREE.BufferAttribute(scales, 1));
    const particleMaterial = new THREE.PointsMaterial({
      color: 0xffd86b,
      size: 0.04,
      transparent: true,
      opacity: 0.7,
      sizeAttenuation: true,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    });
    const particles = new THREE.Points(particlesGeom, particleMaterial);
    scene.add(particles);
    const mouse = {
      x: 0,
      y: 0,
      tx: 0,
      ty: 0
    };
    const onMouseMove = e => {
      const rect = mount.getBoundingClientRect();
      mouse.tx = ((e.clientX - rect.left) / rect.width - 0.5) * 2;
      mouse.ty = ((e.clientY - rect.top) / rect.height - 0.5) * 2;
    };
    window.addEventListener("mousemove", onMouseMove);
    let frameId = null;
    const clock = new THREE.Clock();
    const layoutFor = p => p === 0 ? {
      x: 2.6,
      y: 0.0,
      s: 1.0
    } : {
      x: 3.9,
      y: 0.7,
      s: 0.66
    };
    const initL = layoutFor(pageRef.current);
    const base = {
      x: initL.x,
      y: initL.y,
      s: initL.s
    };
    const animate = () => {
      const elapsed = clock.getElapsedTime();
      const speed = speedRef.current;
      mouse.x += (mouse.tx - mouse.x) * 0.04;
      mouse.y += (mouse.ty - mouse.y) * 0.04;
      const target = layoutFor(pageRef.current);
      base.x += (target.x - base.x) * 0.045;
      base.y += (target.y - base.y) * 0.045;
      base.s += (target.s - base.s) * 0.045;
      group.rotation.y += 0.0024 * speed;
      group.rotation.x = mouse.y * 0.12;
      group.position.x = base.x + mouse.x * 0.15;
      group.position.y = base.y;
      group.scale.setScalar(base.s);
      core.rotation.x += 0.0035 * speed;
      core.rotation.y += 0.0025 * speed;
      orbiters.forEach((m, i) => {
        const ud = m.userData;
        const t = elapsed * 0.4 * speed + ud.phase;
        m.position.x = Math.cos(ud.angle + t * 0.3) * ud.radius;
        m.position.z = Math.sin(ud.angle + t * 0.3) * ud.radius;
        m.position.y = Math.sin(t + ud.phase) * 0.8;
        m.rotation.x += 0.01 * speed;
        m.rotation.y += 0.013 * speed;
      });
      ring1.rotation.z += 0.001 * speed;
      ring2.rotation.y += 0.0015 * speed;
      ring3.rotation.x += 0.0008 * speed;
      particles.rotation.y += 0.0004;
      const pPos = particles.geometry.attributes.position.array;
      for (let i = 1; i < pPos.length; i += 3) {
        pPos[i] += Math.sin(elapsed * 0.5 + i * 0.1) * 0.0008;
      }
      particles.geometry.attributes.position.needsUpdate = true;
      renderer.render(scene, camera);
      frameId = requestAnimationFrame(animate);
    };
    animate();
    const onResize = () => {
      const w = mount.clientWidth;
      const h = mount.clientHeight;
      camera.aspect = w / h;
      fitCamera(w, h);
      camera.updateProjectionMatrix();
      renderer.setSize(w, h);
    };
    window.addEventListener("resize", onResize);
    let ro = null;
    if (typeof ResizeObserver !== "undefined") {
      ro = new ResizeObserver(() => onResize());
      ro.observe(mount);
    }
    const tA = setTimeout(onResize, 400);
    const tB = setTimeout(onResize, 1200);
    sceneRef.current = {
      scene,
      renderer,
      goldMaterial,
      edgesMat
    };
    return () => {
      cancelAnimationFrame(frameId);
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("resize", onResize);
      if (ro) ro.disconnect();
      clearTimeout(tA);
      clearTimeout(tB);
      renderer.dispose();
      coreGeom.dispose();
      edgesGeom.dispose();
      orbiterGeom.dispose();
      ringGeom1.dispose();
      ringGeom2.dispose();
      ringGeom3.dispose();
      particlesGeom.dispose();
      goldMaterial.dispose();
      goldDarkMaterial.dispose();
      particleMaterial.dispose();
      edgesMat.dispose();
      if (renderer.domElement.parentNode === mount) {
        mount.removeChild(renderer.domElement);
      }
    };
  }, [goldColor, particleDensity, threeReady]);
  return React.createElement("div", {
    ref: mountRef,
    id: "three-bg",
    className: threeReady ? "three-on" : ""
  });
}
function ThreePillar({
  shape = "octa",
  goldColor = "#D4AF37"
}) {
  const mountRef = useRef(null);
  const threeReady = useThreeReady();
  useEffect(() => {
    const mount = mountRef.current;
    if (!mount || typeof THREE === "undefined") return;
    const width = mount.clientWidth;
    const height = mount.clientHeight;
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(40, width / height, 0.1, 50);
    camera.position.set(0, 0, 5);
    const renderer = new THREE.WebGLRenderer({
      antialias: true,
      alpha: true
    });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.setSize(width, height);
    renderer.setClearColor(0x000000, 0);
    mount.appendChild(renderer.domElement);
    const ambient = new THREE.AmbientLight(0x1a1610, 0.4);
    scene.add(ambient);
    const key = new THREE.PointLight(0xffd86b, 2.5, 15);
    key.position.set(3, 3, 4);
    scene.add(key);
    const fill = new THREE.PointLight(0xb8860b, 1.5, 15);
    fill.position.set(-3, -2, 3);
    scene.add(fill);
    const rim = new THREE.PointLight(0xffe680, 2, 12);
    rim.position.set(-1, 2, -3);
    scene.add(rim);
    const material = new THREE.MeshStandardMaterial({
      color: new THREE.Color(goldColor),
      metalness: 1.0,
      roughness: 0.22
    });
    let geom;
    if (shape === "octa") geom = new THREE.OctahedronGeometry(1.1, 0);else if (shape === "icosa") geom = new THREE.IcosahedronGeometry(1.05, 0);else if (shape === "tetra") geom = new THREE.TetrahedronGeometry(1.25, 0);else geom = new THREE.DodecahedronGeometry(1, 0);
    const mesh = new THREE.Mesh(geom, material);
    scene.add(mesh);
    const edgesGeom = new THREE.EdgesGeometry(geom);
    const edgesMat = new THREE.LineBasicMaterial({
      color: 0xfff0a0,
      transparent: true,
      opacity: 0.5
    });
    const edges = new THREE.LineSegments(edgesGeom, edgesMat);
    mesh.add(edges);
    let frameId;
    const animate = () => {
      mesh.rotation.x += 0.005;
      mesh.rotation.y += 0.008;
      renderer.render(scene, camera);
      frameId = requestAnimationFrame(animate);
    };
    animate();
    const onResize = () => {
      const w = mount.clientWidth;
      const h = mount.clientHeight;
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
      renderer.setSize(w, h);
    };
    window.addEventListener("resize", onResize);
    return () => {
      cancelAnimationFrame(frameId);
      window.removeEventListener("resize", onResize);
      geom.dispose();
      edgesGeom.dispose();
      material.dispose();
      edgesMat.dispose();
      renderer.dispose();
      if (renderer.domElement.parentNode === mount) {
        mount.removeChild(renderer.domElement);
      }
    };
  }, [shape, goldColor, threeReady]);
  return React.createElement("div", {
    ref: mountRef,
    style: {
      width: "100%",
      height: "140px"
    }
  });
}
Object.assign(window, {
  ThreeHero,
  ThreePillar
});
})();

/* ===== sections.jsx ===== */
(function () {
const {
  useEffect,
  useRef,
  useState
} = React;
function Hero({
  t
}) {
  return React.createElement("section", {
    className: "hero",
    id: "top",
    "data-screen-label": "00 Hero"
  }, React.createElement("div", {
    className: "hero-bg-grid"
  }), React.createElement("div", {
    className: "container hero-inner"
  }, React.createElement("div", {
    className: "hero-meta page-in"
  }, React.createElement("span", {
    className: "eyebrow"
  }, t.hero.eyebrow), React.createElement("div", null, React.createElement("h1", {
    className: "hero-title"
  }, React.createElement("span", {
    className: "row"
  }, t.hero.title1), React.createElement("span", {
    className: "row gold"
  }, t.hero.title2)), React.createElement("div", {
    className: "hero-en"
  }, t.hero.en)), React.createElement("p", {
    className: "hero-sub"
  }, t.hero.sub), React.createElement("div", {
    className: "hero-cta"
  }, React.createElement("a", {
    href: "#about",
    "data-pageto": "1",
    className: "btn btn-solid"
  }, t.hero.cta1, " ", React.createElement("span", {
    className: "arrow"
  }, "\u2192")), React.createElement("a", {
    href: "#contact",
    "data-pageto": "6",
    className: "btn"
  }, t.hero.cta2, " ", React.createElement("span", {
    className: "arrow"
  }, "\u2192")))), React.createElement("div", {
    className: "hero-3d-col",
    "aria-hidden": "true"
  })), React.createElement("div", {
    className: "scroll-cue"
  }, React.createElement("span", null, t.hero.scroll), React.createElement("span", {
    className: "line"
  })), React.createElement("div", {
    className: "hero-ticker"
  }, t.hero.ticker.map((tick, i) => React.createElement("div", {
    key: i,
    className: "hero-ticker-item"
  }, React.createElement("span", {
    className: "dot"
  }), React.createElement("span", null, tick)))));
}
function About({
  t
}) {
  return React.createElement("section", {
    className: "section",
    id: "about",
    "data-screen-label": "01 About"
  }, React.createElement("div", {
    className: "container page-in"
  }, React.createElement("div", {
    className: "section-num"
  }, t.about.num), React.createElement("div", {
    className: "section-head"
  }, React.createElement("h2", {
    className: "section-title"
  }, t.about.title, React.createElement("br", null), React.createElement("span", {
    className: "em"
  }, t.about.titleEm), React.createElement("br", null), t.about.titleSub), React.createElement("p", {
    className: "lead"
  }, t.about.lead)), React.createElement("div", {
    className: "about-grid"
  }, React.createElement("div", {
    className: "about-visual brand-plaque"
  }, React.createElement("div", {
    className: "bp-grid"
  }), React.createElement("div", {
    className: "bp-inner"
  }, React.createElement("div", {
    className: "bp-eyebrow"
  }, "Genesis International Capital"), React.createElement("div", {
    className: "bp-mark"
  }, "GS"), React.createElement("div", {
    className: "bp-line"
  }), React.createElement("div", {
    className: "bp-zh"
  }, t.locale === "zh" ? "創世紀國際投資" : "Genesis Capital"), React.createElement("div", {
    className: "bp-tags"
  }, "AI Quant \xB7 Est. 2025 \xB7 Taichung"))), React.createElement("div", null, React.createElement("p", {
    className: "lead",
    style: {
      marginBottom: 20
    }
  }, t.about.body1), React.createElement("p", {
    className: "lead"
  }, t.about.body2), React.createElement("div", {
    className: "about-stats"
  }, t.about.stats.map((s, i) => React.createElement("div", {
    key: i,
    className: "about-stat"
  }, React.createElement("div", {
    className: "num"
  }, s.num, React.createElement("span", {
    className: "unit"
  }, s.unit)), React.createElement("div", {
    className: "label"
  }, s.label))))))));
}
function Services({
  t
}) {
  return React.createElement("section", {
    className: "section",
    id: "services",
    "data-screen-label": "02 Services"
  }, React.createElement("div", {
    className: "container page-in"
  }, React.createElement("div", {
    className: "section-num"
  }, t.services.num), React.createElement("div", {
    className: "section-head"
  }, React.createElement("h2", {
    className: "section-title"
  }, t.services.title, React.createElement("br", null), React.createElement("span", {
    className: "em"
  }, t.services.titleEn)), React.createElement("p", {
    className: "lead"
  }, t.services.lead)), React.createElement("div", {
    className: "services-grid"
  }, t.services.items.map((item, i) => React.createElement("div", {
    key: i,
    className: "service-card"
  }, React.createElement("div", {
    className: "num"
  }, String(i + 1).padStart(2, "0"), " \u2014"), React.createElement("h3", null, item.en), React.createElement("div", {
    className: "en"
  }, item.zh), React.createElement("p", null, item.desc), React.createElement("div", {
    className: "arrow-bottom"
  }, "\u2192"))))));
}
function Philosophy({
  t,
  goldColor,
  active
}) {
  const shapes = ["dodeca", "icosa", "octa"];
  return React.createElement("section", {
    className: "section philosophy",
    id: "philosophy",
    "data-screen-label": "03 Philosophy"
  }, React.createElement("div", {
    className: "container page-in"
  }, React.createElement("div", {
    className: "section-num",
    style: {
      textAlign: "center"
    }
  }, t.philosophy.num), React.createElement("h2", {
    className: "philosophy-quote"
  }, t.philosophy.quote1, React.createElement("br", null), React.createElement("span", {
    className: "em"
  }, t.philosophy.quote2), React.createElement("br", null), t.philosophy.quote3), React.createElement("div", {
    className: "philosophy-pillars"
  }, t.philosophy.pillars.map((p, i) => React.createElement("div", {
    key: i,
    className: "pillar"
  }, active && React.createElement(ThreePillar, {
    shape: shapes[i],
    goldColor: goldColor
  }), React.createElement("h4", null, p.en), React.createElement("div", {
    className: "en"
  }, "\u2014 ", p.zh, " \u2014"), React.createElement("p", null, p.desc))))));
}
function Team({
  t
}) {
  return React.createElement("section", {
    className: "section",
    id: "team",
    "data-screen-label": "04 Team"
  }, React.createElement("div", {
    className: "container page-in"
  }, React.createElement("div", {
    className: "section-num"
  }, t.team.num), React.createElement("div", {
    className: "section-head"
  }, React.createElement("h2", {
    className: "section-title"
  }, t.team.title, React.createElement("br", null), React.createElement("span", {
    className: "em"
  }, t.team.titleEn)), React.createElement("p", {
    className: "lead"
  }, t.team.lead)), React.createElement("div", {
    className: "team-list"
  }, t.team.members.map((m, i) => React.createElement("div", {
    key: i,
    className: "team-row"
  }, React.createElement("div", {
    className: "idx"
  }, String(i + 1).padStart(2, "0")), React.createElement("div", {
    className: "dept"
  }, React.createElement("h4", null, m.name), React.createElement("div", {
    className: "role"
  }, m.role)), React.createElement("p", {
    className: "bio"
  }, m.bio))))));
}
function Space({
  t
}) {
  return React.createElement("section", {
    className: "section",
    id: "space",
    "data-screen-label": "05 Space"
  }, React.createElement("div", {
    className: "container page-in"
  }, React.createElement("div", {
    className: "section-num"
  }, t.space.num), React.createElement("div", {
    className: "section-head"
  }, React.createElement("h2", {
    className: "section-title"
  }, t.space.title, React.createElement("br", null), React.createElement("span", {
    className: "em"
  }, t.space.titleEn)), React.createElement("p", {
    className: "lead"
  }, t.space.lead)), React.createElement("div", {
    className: "space-grid"
  }, t.space.items.map((it, i) => React.createElement("figure", {
    key: i,
    className: "space-fig"
  }, React.createElement("div", {
    className: "space-img",
    style: {
      backgroundImage: `url("${it.img}")`
    }
  }), React.createElement("figcaption", {
    className: "space-cap"
  }, React.createElement("span", {
    className: "lbl"
  }, it.label), React.createElement("span", {
    className: "ttl"
  }, it.title), React.createElement("span", {
    className: "dsc"
  }, it.desc)))))));
}
function Milestones({
  t
}) {
  return React.createElement("section", {
    className: "section milestones",
    id: "milestones",
    "data-screen-label": "05 Milestones"
  }, React.createElement("div", {
    className: "container page-in"
  }, React.createElement("div", {
    className: "section-num"
  }, t.milestones.num), React.createElement("div", {
    className: "section-head"
  }, React.createElement("h2", {
    className: "section-title"
  }, t.milestones.title, React.createElement("br", null), React.createElement("span", {
    className: "em"
  }, t.milestones.titleEn)), React.createElement("p", {
    className: "lead"
  }, t.milestones.lead)), React.createElement("div", {
    className: "timeline-h"
  }, t.milestones.items.map((item, i) => React.createElement("div", {
    key: i,
    className: "ms-h"
  }, React.createElement("div", {
    className: "yr"
  }, item.year), React.createElement("div", {
    className: "ms-dot"
  }), React.createElement("div", {
    className: "ms-body"
  }, React.createElement("h4", null, item.title), React.createElement("p", null, item.desc)))))));
}
function Contact({
  t
}) {
  return React.createElement("section", {
    className: "section contact",
    id: "contact",
    "data-screen-label": "06 Contact"
  }, React.createElement("div", {
    className: "container page-in"
  }, React.createElement("div", {
    className: "section-num"
  }, t.contact.num), React.createElement("div", {
    className: "section-head"
  }, React.createElement("h2", {
    className: "section-title"
  }, t.contact.title, React.createElement("br", null), React.createElement("span", {
    className: "em"
  }, t.contact.titleEm, ".")), React.createElement("p", {
    className: "lead"
  }, t.contact.lead)), React.createElement("div", {
    className: "contact-grid contact-grid-solo"
  }, React.createElement("div", {
    className: "contact-info-block"
  }, t.contact.info.map((row, i) => React.createElement("div", {
    key: i,
    className: "row"
  }, React.createElement("div", {
    className: "label"
  }, row.label), React.createElement("div", {
    className: "val",
    style: {
      whiteSpace: "pre-line"
    }
  }, row.val))))), React.createElement("div", {
    className: "contact-footer"
  }, React.createElement("div", null, t.footer.copy), React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 8
    }
  }, React.createElement("span", {
    style: {
      width: 6,
      height: 6,
      background: "var(--gold)",
      borderRadius: "50%"
    }
  }), t.footer.built))));
}
Object.assign(window, {
  Hero,
  About,
  Services,
  Philosophy,
  Team,
  Space,
  Milestones,
  Contact
});
})();

/* ===== app.jsx ===== */
(function () {
const {
  useState,
  useEffect,
  useRef,
  useCallback
} = React;
const TWEAK_DEFAULTS = {
  "goldColor": "#D4AF37",
  "rotationSpeed": 1,
  "particleDensity": 1,
  "language": "zh",
  "transition": "sweep"
};
const PAGES = [{
  id: "top",
  labelKey: "home",
  num: "01"
}, {
  id: "about",
  labelKey: "about",
  num: "02"
}, {
  id: "services",
  labelKey: "services",
  num: "03"
}, {
  id: "philosophy",
  labelKey: "philosophy",
  num: "04"
}, {
  id: "team",
  labelKey: "team",
  num: "05"
}, {
  id: "space",
  labelKey: "space",
  num: "06"
}, {
  id: "milestones",
  labelKey: "milestones",
  num: "07"
}, {
  id: "contact",
  labelKey: "contact",
  num: "08"
}];
function Nav({
  t,
  locale,
  setLocale,
  currentPage,
  goTo
}) {
  const links = [{
    id: 1,
    label: t.nav.about
  }, {
    id: 2,
    label: t.nav.services
  }, {
    id: 3,
    label: t.nav.philosophy
  }, {
    id: 4,
    label: t.nav.team
  }, {
    id: 5,
    label: t.nav.space
  }, {
    id: 6,
    label: t.nav.milestones
  }, {
    id: 7,
    label: t.nav.contact
  }];
  return React.createElement("nav", {
    className: "nav scrolled"
  }, React.createElement("a", {
    href: "#top",
    className: "nav-logo",
    onClick: e => {
      e.preventDefault();
      goTo(0);
    }
  }, React.createElement("div", {
    className: "nav-logo-mark"
  }, "GS"), React.createElement("div", {
    className: "nav-logo-text"
  }, React.createElement("span", {
    className: "zh"
  }, locale === "zh" ? "創世紀國際投資" : "Genesis Capital"), React.createElement("span", {
    className: "en"
  }, "GS \xB7 EST. 2025"))), React.createElement("div", {
    className: "nav-links"
  }, links.map(l => React.createElement("a", {
    key: l.id,
    href: `#${PAGES[l.id].id}`,
    className: `nav-link ${currentPage === l.id ? "active" : ""}`,
    onClick: e => {
      e.preventDefault();
      goTo(l.id);
    }
  }, l.label)), React.createElement("div", {
    className: "lang-toggle lang-keep"
  }, React.createElement("button", {
    className: `lang-btn ${locale === "zh" ? "active" : ""}`,
    onClick: () => setLocale("zh")
  }, "\u7E41\u4E2D"), React.createElement("button", {
    className: `lang-btn ${locale === "en" ? "active" : ""}`,
    onClick: () => setLocale("en")
  }, "EN")), React.createElement("button", {
    className: "nav-burger",
    "aria-label": "menu"
  }, React.createElement("span", null), React.createElement("span", null), React.createElement("span", null))));
}
function Pager({
  t,
  currentPage,
  goTo,
  locale
}) {
  const labels = locale === "zh" ? ["首頁", t.nav.about, t.nav.services, t.nav.philosophy, t.nav.team, t.nav.space, t.nav.milestones, t.nav.contact] : ["Home", "About", "Services", "Philosophy", "Team", "Our Space", "Roadmap", "Contact"];
  return React.createElement("div", {
    className: "pager",
    role: "navigation"
  }, PAGES.map((p, i) => React.createElement("button", {
    key: p.id,
    className: `pager-btn ${i === currentPage ? "active" : ""}`,
    onClick: () => goTo(i),
    "aria-label": labels[i]
  }, React.createElement("span", {
    className: "pager-num"
  }, p.num), React.createElement("span", {
    className: "pager-label"
  }, labels[i]))));
}
function PageCounter({
  currentPage,
  total
}) {
  return React.createElement("div", {
    className: "page-counter"
  }, React.createElement("span", {
    className: "cur"
  }, String(currentPage + 1).padStart(2, "0")), React.createElement("span", {
    className: "slash"
  }, "/"), React.createElement("span", {
    className: "tot"
  }, String(total).padStart(2, "0")));
}
function Intro({
  locale,
  hide,
  lift
}) {
  return React.createElement("div", {
    className: `intro ${lift ? "lift" : ""} ${hide ? "done" : ""}`
  }, React.createElement("div", {
    className: "intro-stage"
  }, React.createElement("div", {
    className: "intro-mark"
  }, "GS"), React.createElement("div", {
    className: "intro-line"
  }), React.createElement("div", {
    className: "intro-title"
  }, React.createElement("div", {
    className: "zh"
  }, locale === "zh" ? "創世紀國際投資" : "GENESIS INVESTMENT"), React.createElement("div", {
    className: "en"
  }, "EST \xB7 2025 \xB7 TAICHUNG"))), React.createElement("div", {
    className: "intro-counter"
  }, "LOADING \xB7 ", locale === "zh" ? "載入中" : "INITIALIZING"), React.createElement("div", {
    className: "intro-bars"
  }, React.createElement("span", null), React.createElement("span", null)));
}
function App() {
  const [tweaks, setTweak] = useTweaks(TWEAK_DEFAULTS);
  const [locale, setLocale] = useState(tweaks.language || "zh");
  const [currentPage, setCurrentPage] = useState(0);
  const lockRef = useRef(false);
  const wheelAccum = useRef(0);
  useEffect(() => {
    const bs = document.getElementById("boot-splash");
    if (bs) {
      bs.classList.add("hide");
      setTimeout(() => bs.remove(), 600);
    }
    document.body.classList.add("first-load");
    const tClear = setTimeout(() => document.body.classList.remove("first-load"), 1600);
    return () => {
      clearTimeout(tClear);
    };
  }, []);
  useEffect(() => {
    if (tweaks.language !== locale) setTweak("language", locale);
  }, [locale]);
  useEffect(() => {
    if (tweaks.language && tweaks.language !== locale) setLocale(tweaks.language);
  }, [tweaks.language]);
  const t = I18N[locale] || I18N.zh;
  useEffect(() => {
    document.documentElement.lang = locale === "zh" ? "zh-Hant" : "en";
  }, [locale]);
  const goTo = useCallback(target => {
    if (lockRef.current) return;
    if (target < 0 || target >= PAGES.length) return;
    setCurrentPage(prev => {
      if (prev === target) return prev;
      lockRef.current = true;
      setTimeout(() => {
        lockRef.current = false;
      }, 350);
      return target;
    });
  }, []);
  useEffect(() => {
    let cooldown = false;
    let touchStartY = null;
    const tryNavWheel = deltaY => {
      if (cooldown || lockRef.current) return;
      const activeEl = document.querySelector(".page.active");
      if (activeEl) {
        const canScrollDown = activeEl.scrollHeight - activeEl.clientHeight - activeEl.scrollTop > 4;
        const canScrollUp = activeEl.scrollTop > 4;
        if (deltaY > 0 && canScrollDown) return;
        if (deltaY < 0 && canScrollUp) return;
      }
      wheelAccum.current += deltaY;
      if (Math.abs(wheelAccum.current) < 40) return;
      cooldown = true;
      setTimeout(() => {
        cooldown = false;
        wheelAccum.current = 0;
      }, 400);
      if (wheelAccum.current > 0) goTo(currentPage + 1);else goTo(currentPage - 1);
      wheelAccum.current = 0;
    };
    const onWheel = e => {
      tryNavWheel(e.deltaY);
    };
    const onKey = e => {
      if (e.target.tagName === "INPUT" || e.target.tagName === "TEXTAREA" || e.target.tagName === "SELECT") return;
      if (e.key === "ArrowDown" || e.key === "PageDown" || e.key === " ") {
        e.preventDefault();
        goTo(currentPage + 1);
      } else if (e.key === "ArrowUp" || e.key === "PageUp") {
        e.preventDefault();
        goTo(currentPage - 1);
      } else if (e.key === "Home") {
        e.preventDefault();
        goTo(0);
      } else if (e.key === "End") {
        e.preventDefault();
        goTo(PAGES.length - 1);
      }
    };
    const onTouchStart = e => {
      touchStartY = e.touches[0].clientY;
    };
    const onTouchEnd = e => {
      if (touchStartY == null) return;
      const dy = touchStartY - e.changedTouches[0].clientY;
      if (Math.abs(dy) < 50) return;
      tryNavWheel(dy);
      touchStartY = null;
    };
    window.addEventListener("wheel", onWheel, {
      passive: true
    });
    window.addEventListener("keydown", onKey);
    window.addEventListener("touchstart", onTouchStart, {
      passive: true
    });
    window.addEventListener("touchend", onTouchEnd, {
      passive: true
    });
    return () => {
      window.removeEventListener("wheel", onWheel);
      window.removeEventListener("keydown", onKey);
      window.removeEventListener("touchstart", onTouchStart);
      window.removeEventListener("touchend", onTouchEnd);
    };
  }, [currentPage, goTo]);
  useEffect(() => {
    const fromHash = () => {
      const hash = location.hash.replace("#", "");
      const idx = PAGES.findIndex(p => p.id === hash);
      if (idx >= 0) goTo(idx);
    };
    fromHash();
    window.addEventListener("hashchange", fromHash);
    return () => window.removeEventListener("hashchange", fromHash);
  }, [goTo]);
  const renderPage = i => {
    const active = i === currentPage;
    switch (i) {
      case 0:
        return React.createElement(Hero, {
          t: t
        });
      case 1:
        return React.createElement(About, {
          t: t
        });
      case 2:
        return React.createElement(Services, {
          t: t
        });
      case 3:
        return React.createElement(Philosophy, {
          t: t,
          goldColor: tweaks.goldColor,
          active: active
        });
      case 4:
        return React.createElement(Team, {
          t: t
        });
      case 5:
        return React.createElement(Space, {
          t: t
        });
      case 6:
        return React.createElement(Milestones, {
          t: t
        });
      case 7:
        return React.createElement(Contact, {
          t: t
        });
      default:
        return null;
    }
  };
  const pageClass = i => i === currentPage ? "page active" : "page";
  useEffect(() => {
    document.body.setAttribute("data-page", currentPage === 0 ? "hero" : "content");
  }, [currentPage]);
  return React.createElement(React.Fragment, null, React.createElement(ThreeHero, {
    goldColor: tweaks.goldColor,
    rotationSpeed: tweaks.rotationSpeed,
    particleDensity: tweaks.particleDensity,
    page: currentPage
  }), React.createElement("div", {
    id: "bg-scrim"
  }), React.createElement(Nav, {
    t: t,
    locale: locale,
    setLocale: setLocale,
    currentPage: currentPage,
    goTo: goTo
  }), React.createElement("div", {
    className: "page-shell"
  }, PAGES.map((p, i) => React.createElement("div", {
    key: i,
    className: pageClass(i),
    "aria-hidden": i !== currentPage
  }, renderPage(i)))), React.createElement(Pager, {
    t: t,
    currentPage: currentPage,
    goTo: goTo,
    locale: locale
  }), React.createElement(PageCounter, {
    currentPage: currentPage,
    total: PAGES.length
  }), React.createElement(TweaksPanel, {
    title: "Tweaks"
  }, React.createElement(TweakSection, {
    label: locale === "zh" ? "視覺" : "Visual"
  }), React.createElement(TweakColor, {
    label: locale === "zh" ? "金色色調" : "Gold tone",
    value: tweaks.goldColor,
    onChange: v => setTweak("goldColor", v),
    options: ["#D4AF37", "#C9A961", "#E8C77A", "#B8860B", "#F4D03F"]
  }), React.createElement(TweakSlider, {
    label: locale === "zh" ? "3D 旋轉速度" : "3D rotation",
    value: tweaks.rotationSpeed,
    min: 0,
    max: 3,
    step: 0.1,
    onChange: v => setTweak("rotationSpeed", v),
    unit: "\xD7"
  }), React.createElement(TweakSlider, {
    label: locale === "zh" ? "粒子密度" : "Particles",
    value: tweaks.particleDensity,
    min: 0,
    max: 2,
    step: 0.1,
    onChange: v => setTweak("particleDensity", v),
    unit: "\xD7"
  }), React.createElement(TweakSection, {
    label: locale === "zh" ? "語言" : "Language"
  }), React.createElement(TweakRadio, {
    label: locale === "zh" ? "語系" : "Locale",
    value: locale,
    options: [{
      value: "zh",
      label: "繁中"
    }, {
      value: "en",
      label: "English"
    }],
    onChange: v => {
      setLocale(v);
      setTweak("language", v);
    }
  })));
}
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(React.createElement(App, null));
})();
